#!/bin/sh
# lf preview script

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

case "$(file -Lb --mime-type -- "$file")" in
    image/*)
        chafa -f sixel -s "${w}x${h}" --animate off "$file"
        exit 1
        ;;
    video/*)
        # Thumbnail at 10% of video
        ffmpegthumbnailer -i "$file" -o /tmp/lf_thumb.png -s 0 -q 5
        chafa -f sixel -s "${w}x${h}" /tmp/lf_thumb.png
        exit 1
        ;;
    audio/*)
        mediainfo "$file" 2>/dev/null || file -b "$file"
        ;;
    application/pdf)
        pdftoppm -png -f 1 -singlefile "$file" /tmp/lf_pdf
        chafa -f sixel -s "${w}x${h}" /tmp/lf_pdf.png
        exit 1
        ;;
    application/zip)
        unzip -l "$file"
        ;;
    application/x-tar|application/gzip|application/x-xz|application/x-bzip2)
        tar -tf "$file"
        ;;
    application/x-rar)
        unrar l "$file"
        ;;
    application/x-7z-compressed)
        7z l "$file"
        ;;
    application/json)
        jq -C . "$file" 2>/dev/null || cat "$file"
        ;;
    text/*|application/javascript|application/xml|application/x-shellscript)
        bat --color=always --style=plain --paging=never -r :100 "$file" 2>/dev/null || head -100 "$file"
        ;;
    *)
        file -b "$file"
        ;;
esac
