---
- name: Amfora
  tags: [amfora]
  block:
    - name: Install amfora
      community.general.xbps:
        update_cache: false
        name: amfora
        state: present
      become: true

    - name: Create amfora config directory
      ansible.builtin.file:
        path: "{{ user_home }}/.config/amfora"
        state: directory
        mode: "0755"

    - name: Deploy amfora configuration
      ansible.builtin.copy:
        src: amfora/config.toml
        dest: "{{ user_home }}/.config/amfora/config.toml"
        mode: "0644"
