---
- name: Fastfetch
  tags: [fastfetch]
  block:
    - name: Install fastfetch
      community.general.xbps:
        update_cache: false
        name: fastfetch
        state: present
      become: true

    - name: Create fastfetch config directory
      ansible.builtin.file:
        path: "{{ user_home }}/.config/fastfetch"
        state: directory
        mode: "0755"

    - name: Deploy fastfetch config
      ansible.builtin.copy:
        src: fastfetch/config.jsonc
        dest: "{{ user_home }}/.config/fastfetch/config.jsonc"
        mode: "0644"
