---
- name: Kanshi
  tags: [kanshi]
  block:
    - name: Install kanshi
      community.general.xbps:
        update_cache: false
        name: kanshi
        state: present
      become: true

    - name: Create kanshi config directory
      ansible.builtin.file:
        path: "{{ user_home }}/.config/kanshi"
        state: directory
        mode: "0755"

    - name: Deploy kanshi config
      ansible.builtin.copy:
        src: kanshi/config
        dest: "{{ user_home }}/.config/kanshi/config"
        mode: "0644"
