---
- name: Install micro
  community.general.xbps:
    name: micro
    state: present
  become: true
  tags: [micro]

- name: Create micro config directory
  ansible.builtin.file:
    path: "{{ user_home }}/.config/micro"
    state: directory
    mode: "0755"
  tags: [micro]

- name: Deploy micro settings.json
  ansible.builtin.copy:
    src: micro/settings.json
    dest: "{{ user_home }}/.config/micro/settings.json"
    mode: "0644"
  tags: [micro]

- name: Deploy micro bindings.json
  ansible.builtin.copy:
    src: micro/bindings.json
    dest: "{{ user_home }}/.config/micro/bindings.json"
    mode: "0644"
  tags: [micro]
