---
- name: Install obsidian from nix unstable
  ansible.builtin.command:
    cmd: nix profile install nixpkgs#obsidian --extra-experimental-features nix-command --extra-experimental-features flakes --impure
  environment:
    NIXPKGS_ALLOW_UNFREE: "1"
  register: obsidian_install
  changed_when: "'already installed' not in obsidian_install.stderr"
  failed_when: obsidian_install.rc != 0 and 'already installed' not in obsidian_install.stderr
  tags: [obsidian]
