---
- name: Create PARA folder structure
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - ~/Documents/0-Inbox
    - ~/Documents/1-Projects
    - ~/Documents/2-Areas
    - ~/Documents/3-Resources
    - ~/Documents/4-Archives
  tags: para

- name: Create notepad.md file
  ansible.builtin.copy:
    content: |
      
      Notepad
      =======
    dest: ~/Documents/0-Inbox/notepad.md
    force: no
    mode: '0644'
  tags: para

- name: Add move-downloads to user crontab
  ansible.builtin.cron:
    name: "Move Downloads to Inbox"
    minute: "0"
    hour: "*"
    job: "fish -c move-downloads"
    user: "{{ ansible_user_id }}"
  tags: para
