---
- name: Para
  tags: [para]
  block:
    - name: Create PARA folder structure
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - ~/0-Inbox
        - ~/1-Projects
        - ~/2-Areas
        - ~/3-Resources
        - ~/3-Resources/music
        - ~/3-Resources/pics
        - ~/3-Resources/videos
        - ~/4-Archives

    - name: Create notepad.md file
      ansible.builtin.copy:
        content: |

          Notepad
          =======
        dest: ~/0-Inbox/notepad.md
        force: no
        mode: '0644'

    - name: Remove old move-downloads cron (Downloads = Inbox now)
      ansible.builtin.cron:
        name: "Move Downloads to Inbox"
        state: absent
        user: "{{ ansible_user_id }}"
