---
- name: Install pcmanfm
  community.general.xbps:
    name: pcmanfm
    state: present
  become: true
  tags: [pcmanfm]

- name: Create pcmanfm config directory
  ansible.builtin.file:
    path: "{{ user_home }}/.config/pcmanfm/default"
    state: directory
    mode: "0755"
  tags: [pcmanfm]

- name: Deploy pcmanfm config
  ansible.builtin.copy:
    src: pcmanfm/default
    dest: "{{ user_home }}/.config/pcmanfm/default/pcmanfm.conf"
    mode: "0644"
  tags: [pcmanfm]

- name: Create libfm config directory
  ansible.builtin.file:
    path: "{{ user_home }}/.config/libfm"
    state: directory
    mode: "0755"
  tags: [pcmanfm]

- name: Deploy libfm config
  ansible.builtin.copy:
    content: |
      [config]
      terminal=wezterm
    dest: "{{ user_home }}/.config/libfm/libfm.conf"
    mode: "0644"
  tags: [pcmanfm]

- name: Create file-manager actions directory
  ansible.builtin.file:
    path: "{{ user_home }}/.local/share/file-manager/actions"
    state: directory
    mode: "0755"
  tags: [pcmanfm]

- name: Add extract archive action
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Type=Action
      Name=Extract here
      Icon=package-x-generic
      Profiles=profile-zero;

      [X-Action-Profile profile-zero]
      MimeTypes=application/zip;application/x-tar;application/x-compressed-tar;application/x-bzip-compressed-tar;application/x-xz-compressed-tar;
      Exec=wezterm start sh -c 'case "%f" in *.zip) unzip "%f" -d "${PWD}";; *.tar.gz|*.tgz) tar -xzf "%f" -C "${PWD}";; *.tar.bz2|*.tbz2) tar -xjf "%f" -C "${PWD}";; *.tar.xz) tar -xJf "%f" -C "${PWD}";; *.tar) tar -xf "%f" -C "${PWD}";; esac && echo "\nFinished! Press Enter to close" && read'
      Name=Extract archive
    dest: "{{ user_home }}/.local/share/file-manager/actions/extract.desktop"
    mode: "0644"
  tags: [pcmanfm]

- name: Add compress to zip action
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Type=Action
      Name=Compress to ZIP
      Icon=package-x-generic
      Profiles=profile-zero;

      [X-Action-Profile profile-zero]
      MimeTypes=all/allfiles;inode/directory;
      Exec=wezterm start sh -c 'filename=$(basename "%f"); zip -r "${filename}.zip" "%f" && echo "\nFinished! Press Enter to close" && read'
      Name=Compress to ZIP
    dest: "{{ user_home }}/.local/share/file-manager/actions/compress-zip.desktop"
    mode: "0644"
  tags: [pcmanfm]
