---
- name: Pcmanfm
  tags: [pcmanfm]
  block:
    - name: Install pcmanfm
      community.general.xbps:
        update_cache: false
        name:
          - pcmanfm
          - file-roller
        state: present
      become: true

    - name: Create pcmanfm config directory
      ansible.builtin.file:
        path: "{{ user_home }}/.config/pcmanfm/default"
        state: directory
        mode: "0755"

    - name: Deploy pcmanfm config
      ansible.builtin.copy:
        src: pcmanfm/default
        dest: "{{ user_home }}/.config/pcmanfm/default/pcmanfm.conf"
        mode: "0644"

    - name: Create libfm config directory
      ansible.builtin.file:
        path: "{{ user_home }}/.config/libfm"
        state: directory
        mode: "0755"

    - name: Deploy libfm config
      ansible.builtin.copy:
        src: pcmanfm/libfm.conf
        dest: "{{ user_home }}/.config/libfm/libfm.conf"
        mode: "0644"

    - name: Create file-manager actions directory
      ansible.builtin.file:
        path: "{{ user_home }}/.local/share/file-manager/actions"
        state: directory
        mode: "0755"

    - name: Add extract archive action
      ansible.builtin.copy:
        src: pcmanfm/extract.desktop
        dest: "{{ user_home }}/.local/share/file-manager/actions/extract.desktop"
        mode: "0644"

    - name: Add compress to zip action
      ansible.builtin.copy:
        src: pcmanfm/compress-zip.desktop
        dest: "{{ user_home }}/.local/share/file-manager/actions/compress-zip.desktop"
        mode: "0644"

    - name: Create local applications directory
      ansible.builtin.file:
        path: "{{ user_home }}/.local/share/applications"
        state: directory
        mode: "0755"

    - name: Deploy pcmanfm desktop override
      ansible.builtin.copy:
        src: pcmanfm/pcmanfm.desktop
        dest: "{{ user_home }}/.local/share/applications/pcmanfm.desktop"
        mode: "0644"
