---
- name: Telegram
  tags: [telegram]
  block:
    - name: Install telegram-desktop
      community.general.xbps:
        update_cache: false
        name: telegram-desktop
        state: present
      become: true
