---
# Tide prompt installation

- name: Clone tide repository
  ansible.builtin.git:
    repo: https://github.com/IlanCosman/tide.git
    dest: /tmp/tide-prompt
    version: v6
    depth: 1
  tags: [tide]

- name: Copy tide functions
  ansible.builtin.copy:
    src: /tmp/tide-prompt/functions/
    dest: "{{ user_home }}/.config/fish/functions/"
    mode: "0644"
  tags: [tide]

- name: Copy tide conf.d
  ansible.builtin.copy:
    src: /tmp/tide-prompt/conf.d/
    dest: "{{ user_home }}/.config/fish/conf.d/"
    mode: "0644"
  tags: [tide]

- name: Copy tide completions
  ansible.builtin.copy:
    src: /tmp/tide-prompt/completions/
    dest: "{{ user_home }}/.config/fish/completions/"
    mode: "0644"
  tags: [tide]

- name: Remove tide clone
  ansible.builtin.file:
    path: /tmp/tide-prompt
    state: absent
  tags: [tide]
