---
- name: Tlp
  tags: [tlp]
  become: true
  block:
    - name: Install TLP
      community.general.xbps:
        update_cache: false
        name: tlp
        state: present

    - name: Deploy TLP config
      ansible.builtin.copy:
        src: tlp/tlp.conf
        dest: /etc/tlp.conf
        mode: "0644"

    - name: Enable TLP service
      ansible.builtin.file:
        src: /etc/sv/tlp
        dest: /var/service/tlp
        state: link
