---
- name: Translate
  tags: [translate]
  become: true
  block:
    - name: Install translate-shell and wtype
      community.general.xbps:
        update_cache: false
        name:
          - translate-shell
          - wtype
        state: present
