---
# QEMU/KVM virtualization

- name: Virtualization
  tags: [virtualization, qemu, kvm]
  become: true
  block:
    - name: Install QEMU and KVM packages
      community.general.xbps:
        update_cache: false
        name:
          - qemu
          - libvirt
          - virt-manager
          - dnsmasq
          - bridge-utils
          - iptables
        state: present

    - name: Add user to libvirt group
      ansible.builtin.user:
        name: "{{ username }}"
        groups: libvirt
        append: true

    - name: Enable libvirtd service
      ansible.builtin.file:
        src: /etc/sv/libvirtd
        dest: /var/service/libvirtd
        state: link

    - name: Enable virtlockd service
      ansible.builtin.file:
        src: /etc/sv/virtlockd
        dest: /var/service/virtlockd
        state: link

    - name: Enable virtlogd service
      ansible.builtin.file:
        src: /etc/sv/virtlogd
        dest: /var/service/virtlogd
        state: link
