---
- name: Install VLC
  community.general.xbps:
    name:
      - vlc
    state: present
  become: true
  tags: [vlc]

- name: Create VLC config directory
  ansible.builtin.file:
    path: "{{ user_home }}/.config/vlc"
    state: directory
    mode: "0755"
  tags: [vlc]

- name: Deploy VLC config
  ansible.builtin.copy:
    src: vlc/vlcrc
    dest: "{{ user_home }}/.config/vlc/vlcrc"
    mode: "0644"
  tags: [vlc]
