---
- name: Restart bluetoothd
  ansible.builtin.command: sv restart bluetoothd
  changed_when: true
  become: true

- name: Regenerate GRUB config
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
  changed_when: true
  become: true
