#!/usr/bin/fish
# turn off external speakers
smarthome 1 off 2>/dev/null
# unmount all USB devices before poweroff
for dev in (lsblk -nrpo NAME,TYPE,MOUNTPOINT,RM | awk '$2=="part" && $3!="" && $4=="1" {print $1}')
    udisksctl unmount -b $dev --no-user-interaction 2>/dev/null
end
exec loginctl poweroff
