---
galaxy_info:
  author: mggpie
  description: System base - locale, services, drivers, Nix
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Void Linux
      versions: [all]
dependencies: []
