---
# Load secrets if vault is available
- name: Include secrets
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/secrets.yml"
  failed_when: false
  no_log: true
  tags: [always]

- name: Import dev tasks
  ansible.builtin.import_tasks: dev.yml
- name: Import git tasks
  ansible.builtin.import_tasks: git.yml
- name: Import gh tasks
  ansible.builtin.import_tasks: gh.yml
- name: Import ssh tasks
  ansible.builtin.import_tasks: ssh.yml
- name: Import vscode tasks
  ansible.builtin.import_tasks: vscode.yml
- name: Import zed tasks
  ansible.builtin.import_tasks: zed.yml
- name: Import lite-xl tasks
  ansible.builtin.import_tasks: lite-xl.yml
